"""Real job application tracking — persisted to SQLite."""
import json
import uuid
from datetime import datetime
from typing import Literal, Optional
from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import Response
from pydantic import BaseModel
from database import SessionLocal, JobApplication
from middleware.auth import require_self

router = APIRouter()

# Hard cap — prevents unbounded queries on large accounts
_JOB_QUERY_LIMIT = 1000


class JobIn(BaseModel):
    user_email:      str
    title:           str
    company:         str
    location:        str = ""
    platform:        str
    job_url:         str = ""
    status:          str = "Applied"
    proof:           str = ""
    score:           Optional[int] = None
    score_breakdown: Optional[str] = None


class StatusIn(BaseModel):
    status: Literal["Applied", "Viewed", "Interview", "Rejected"]


@router.get("/stats/{user_email}")
def get_stats(user_email: str, _: str = Depends(require_self)):
    with SessionLocal() as db:
        jobs = db.query(JobApplication).filter(
            JobApplication.user_email == user_email
        ).limit(_JOB_QUERY_LIMIT).all()
        total = len(jobs)
        by_status = {}
        by_platform = {}
        for j in jobs:
            by_status[j.status] = by_status.get(j.status, 0) + 1
            by_platform[j.platform] = by_platform.get(j.platform, 0) + 1
        return {
            "total": total,
            "by_status": by_status,
            "by_platform": by_platform,
        }


@router.get("/{user_email}")
def list_jobs(user_email: str, _: str = Depends(require_self)):
    with SessionLocal() as db:
        jobs = (
            db.query(JobApplication)
            .filter(JobApplication.user_email == user_email)
            .order_by(JobApplication.applied_at.desc())
            .limit(_JOB_QUERY_LIMIT)
            .all()
        )
        return [_fmt(j) for j in jobs]


@router.post("")
def add_job(job: JobIn):
    with SessionLocal() as db:
        record = JobApplication(
            id              = str(uuid.uuid4()),
            user_email      = job.user_email,
            title           = job.title,
            company         = job.company,
            location        = job.location,
            platform        = job.platform,
            job_url         = job.job_url,
            status          = job.status,
            applied_at      = datetime.utcnow(),
            proof           = job.proof,
            score           = job.score,
            score_breakdown = job.score_breakdown,
        )
        db.add(record)
        db.commit()
        db.refresh(record)
        return _fmt(record)


@router.patch("/{job_id}/status")
def update_status(job_id: str, body: StatusIn):
    with SessionLocal() as db:
        job = db.get(JobApplication, job_id)
        if not job:
            raise HTTPException(404, "Job not found")
        job.status = body.status
        db.commit()
        return _fmt(job)


@router.get("/{job_id}/tailored-resume/pdf")
def download_tailored_resume(job_id: str):
    """
    Download the AI-tailored resume PDF for a specific job application.
    The tailored data was generated by the bot worker post-application.
    """
    with SessionLocal() as db:
        job = db.get(JobApplication, job_id)
        if not job:
            raise HTTPException(404, "Job not found")
        if not job.tailored_resume:
            raise HTTPException(404, "No tailored resume available for this application")

        try:
            tailored_data = json.loads(job.tailored_resume)
        except Exception:
            raise HTTPException(500, "Tailored resume data is corrupted")

    # We need a base resume to merge the tailored fields into
    try:
        from database import Resume
        from routers.resume import _serialize_resume

        with SessionLocal() as db:
            base_resume = db.query(Resume).filter_by(
                user_email=job.user_email, is_default=True
            ).first()
            if not base_resume:
                base_resume = db.query(Resume).filter_by(
                    user_email=job.user_email
                ).order_by(Resume.created_at.desc()).first()
            if not base_resume:
                raise HTTPException(404, "No base resume found for this user")
            resume_data = _serialize_resume(base_resume)

        # Merge AI-tailored fields
        if tailored_data.get("professional_summary"):
            resume_data["professional_summary"] = tailored_data["professional_summary"]

        opt_exp_map = {e["id"]: e for e in tailored_data.get("experiences", [])}
        for exp in resume_data.get("experiences", []):
            opt = opt_exp_map.get(exp.get("id"))
            if opt and opt.get("bullets"):
                exp["bullets"] = opt["bullets"]

        from services.resume_builder import build_resume_pdf
        pdf_bytes = build_resume_pdf(resume_data)

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(500, f"PDF generation failed: {e}")

    name = f"tailored_resume_{job.company or 'job'}_{job.title or ''}.pdf".replace(" ", "_")
    return Response(
        content    = pdf_bytes,
        media_type = "application/pdf",
        headers    = {"Content-Disposition": f'attachment; filename="{name}"'},
    )


def _fmt(j: JobApplication) -> dict:
    return {
        "id":             j.id,
        "user_email":     j.user_email,
        "title":          j.title,
        "company":        j.company,
        "location":       j.location,
        "platform":       j.platform,
        "job_url":        j.job_url,
        "status":         j.status,
        "applied_at":     j.applied_at.isoformat() if j.applied_at else None,
        "proof":          j.proof,
        "score":          j.score,
        "score_breakdown": j.score_breakdown,
        "outcome":        j.outcome,
        "has_cover_letter":    bool(j.cover_letter),
        "has_tailored_resume": bool(j.tailored_resume),
    }
